### ISSUE TITLE
"unexpected end of json"

### ISSUE THREAD

**Issue by mikebollandajw** [shebang-labs/terraform-provider-postmark#10]
╷
│ Error: unexpected end of JSON input
│ 
│   with postmark_server.postmark_server_error,
│   on postmark.tf line 5, in resource "postmark_server" "postmark_server_error":
│    5: resource "postmark_server" "postmark_server_error" {
│ 
╵

![image](https://github.com/shebang-labs/terraform-provider-postmark/assets/38316056/6a26877f-4e1f-4581-b4b4-d014aa766c66)

shebang-labs/postmark
0.2.4

resource "postmark_server" "postmark_server_error" {
  name = "ps-${var.be_region}-${lower(var.appname)}"
  delivery_type = "live"
}

**Comment by mikebollandajw** [comment]
![image](https://github.com/shebang-labs/terraform-provider-postmark/assets/38316056/e25fd346-23e4-418c-84f1-0c76918b35f7)

**Comment by phillipuniverse** [comment]
This has been happening for me for about a month now.

@MuhammeedAlaa is this terraform provider still supported? Seems like the API endpoints that this terraform provider uses are no longer available.

**Comment by phillipuniverse** [comment]
@mikebollandajw did this start working for you?

**Comment by mikebollandajw** [comment]
yes its fine now but it caused us some terrible state file problems
